# Generated by Django 4.1.2 on 2022-11-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_staff_social_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='social_whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
