# Generated by Django 4.1.2 on 2022-12-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_staff_profile_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Employee',
        ),
    ]
