# Generated by Django 4.1.2 on 2023-01-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
