# Generated by Django 4.1.2 on 2023-01-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_stat_svg_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='svg_file',
            new_name='svg',
        ),
    ]
