# Generated by Django 4.1.2 on 2023-01-09 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_stat_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
