# Generated by Django 4.1.2 on 2023-01-09 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_stat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='title',
        ),
        migrations.AlterField(
            model_name='special',
            name='image',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
