# Generated by Django 4.1.2 on 2023-01-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_special_title_alter_special_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
