# Generated by Django 4.1.2 on 2023-02-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproduct',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='product_files/'),
        ),
        migrations.AddField(
            model_name='paymentproduct',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
