# Generated by Django 4.1.7 on 2023-03-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentproduct',
            name='url',
        ),
        migrations.AddField(
            model_name='paymentproduct',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentproduct',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
