# Generated by Django 4.1.7 on 2023-03-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_paymentproduct_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
