# Generated by Django 4.1.2 on 2022-12-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_remove_product_supplier_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
