# Generated by Django 4.1.7 on 2023-03-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_remove_product_short_description_product_facts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='short_description',
            new_name='facts',
        ),
        migrations.RemoveField(
            model_name='product',
            name='facts',
        ),
    ]
