# Generated by Django 4.1.7 on 2023-03-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_remove_video_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='web_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
