# Generated by Django 4.1.2 on 2022-12-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_supplier_fact_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sipfact',
            name='supplier',
        ),
    ]
