# Generated by Django 4.1.2 on 2022-12-09 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_remove_sipfact_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipfact',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
    ]
