# Generated by Django 4.1.2 on 2022-12-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0018_image_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
