# Generated by Django 4.1.2 on 2022-12-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='logo_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='marketing_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='models/'),
        ),
    ]
