# Generated by Django 4.1.7 on 2023-03-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproduct',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
