# Generated by Django 4.1.2 on 2022-12-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image1', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='models/')),
                ('image2', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='models/')),
                ('image3', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='models/')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
    ]
