# Generated by Django 4.1.6 on 2023-02-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripepayments', '0002_paymentproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeProduct',
        ),
    ]
