# Generated by Django 4.1.2 on 2022-12-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
