# Generated by Django 4.1.7 on 2023-03-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_video_supplier_alter_video_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='published_at',
        ),
    ]
