# Generated by Django 4.1.7 on 2023-03-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_video_web_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
