# Generated by Django 4.1.7 on 2023-03-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partspage',
            name='supplier_page',
        ),
        migrations.AddField(
            model_name='partspage',
            name='file_link',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
