# Generated by Django 4.1.2 on 2023-01-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0007_alter_partsrequired_quantity_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineregistration',
            name='complete_supply',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='machine_test_run',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='operator_handbook',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='pdi_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='pto_correct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='safety_induction',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
