# Generated by Django 4.1.2 on 2023-01-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0009_alter_partsrequired_quantity_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyclaim',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='labour_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
