# Generated by Django 4.1.2 on 2023-01-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0010_alter_warrantyclaim_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partspage',
            name='catalogue_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partspage',
            name='supplier_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='dealer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='dealer_contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
