# Generated by Django 4.1.2 on 2023-01-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0013_partsrequired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineregistration',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
