# Generated by Django 4.1.2 on 2023-01-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0018_alter_machineregistration_dealer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partsrequired',
            options={},
        ),
        migrations.RenameField(
            model_name='partsrequired',
            old_name='supplier',
            new_name='warranty',
        ),
    ]
