# Generated by Django 4.1.2 on 2023-01-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0019_alter_partsrequired_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantyclaim',
            name='date',
        ),
        migrations.RemoveField(
            model_name='warrantyclaim',
            name='description',
        ),
        migrations.RemoveField(
            model_name='warrantyclaim',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='warrantyclaim',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='warrantyclaim',
            name='quantity_needed',
        ),
    ]
