# Generated by Django 4.1.6 on 2023-03-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0021_warrantyclaim_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyclaim',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Owner Name'),
        ),
    ]
