# Generated by Django 4.1.2 on 2023-01-09 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_stat_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='svg_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
