# Generated by Django 4.1.2 on 2023-01-09 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_svg_file_stat_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
