# Generated by Django 4.1.2 on 2022-11-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Staff',
        ),
    ]
