# Generated by Django 4.1.2 on 2022-11-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_staff_role_alter_staff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='social_whatsapp',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
