# Generated by Django 4.1.7 on 2023-03-04 09:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineRegistration',
            fields=[
                ('dealer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dealer Name')),
                ('dealer_address', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=200, null=True)),
                ('machine_model', models.CharField(blank=True, max_length=200, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('install_date', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=200, null=True)),
                ('complete_supply', models.BooleanField(blank=True, default=False, null=True)),
                ('pdi_complete', models.BooleanField(blank=True, default=False, null=True)),
                ('pto_correct', models.BooleanField(blank=True, default=False, null=True)),
                ('machine_test_run', models.BooleanField(blank=True, default=False, null=True)),
                ('safety_induction', models.BooleanField(blank=True, default=False, null=True)),
                ('operator_handbook', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('completed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPage',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='models/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('dealer', models.CharField(blank=True, max_length=200, null=True)),
                ('dealer_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('machine_model', models.CharField(blank=True, max_length=200, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('install_date', models.CharField(blank=True, max_length=200, null=True)),
                ('failure_date', models.CharField(blank=True, max_length=200, null=True)),
                ('repair_date', models.CharField(blank=True, max_length=200, null=True)),
                ('failure_details', models.TextField(blank=True, null=True)),
                ('repair_details', models.TextField(blank=True, null=True)),
                ('labour_hours', models.CharField(blank=True, max_length=200, null=True)),
                ('completed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PartsRequired',
            fields=[
                ('part_number', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity_needed', models.CharField(blank=True, default=1, max_length=20, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('warranty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareparts.warrantyclaim')),
            ],
        ),
        migrations.CreateModel(
            name='PartsPage',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('catalogue_link', models.URLField(blank=True, null=True)),
                ('supplier_page', models.URLField(blank=True, null=True)),
                ('marketing_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='models/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareparts.supplierpage')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
