# Generated by Django 4.1.2 on 2023-01-14 10:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0003_rename_partpage_partspage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantyclaim',
            name='description',
        ),
        migrations.RemoveField(
            model_name='warrantyclaim',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='warrantyclaim',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='warrantyclaim',
            name='quantity_needed',
        ),
        migrations.AddField(
            model_name='machineregistration',
            name='completed_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='PartsRequired',
            fields=[
                ('part_number', models.IntegerField(blank=True, null=True)),
                ('quantity_needed', models.IntegerField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareparts.supplierpage')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
