# Generated by Django 4.1.2 on 2023-01-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0005_alter_partsrequired_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsrequired',
            name='part_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
