# Generated by Django 4.1.2 on 2023-01-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0008_alter_machineregistration_complete_supply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsrequired',
            name='quantity_needed',
            field=models.CharField(blank=True, default=1, max_length=20, null=True),
        ),
    ]
