# Generated by Django 4.1.2 on 2023-01-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0011_alter_partspage_catalogue_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyclaim',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='part_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='quantity_needed',
            field=models.CharField(blank=True, default=1, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='PartsRequired',
        ),
    ]
