# Generated by Django 4.1.2 on 2023-01-16 18:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0012_warrantyclaim_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsRequired',
            fields=[
                ('part_number', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity_needed', models.CharField(blank=True, default=1, max_length=20, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareparts.warrantyclaim')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
