# Generated by Django 4.1.2 on 2023-01-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0017_remove_machineregistration_date_yyyy_mm_dd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineregistration',
            name='dealer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dealer Name'),
        ),
    ]
