# Generated by Django 4.1.2 on 2023-01-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0020_remove_warrantyclaim_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyclaim',
            name='completed_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
