# Generated by Django 4.1.2 on 2022-12-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_marketing_image_facts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facts',
            new_name='Fact',
        ),
    ]
