# Generated by Django 4.1.2 on 2022-12-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_rename_fact_mxfact_sulkyfact_sipfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='mxfact',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sipfact',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sulkyfact',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
