# Generated by Django 4.1.2 on 2022-12-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_rename_sipfact_fact_remove_sulkyfact_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='social_facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='social_instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
