# Generated by Django 4.1.2 on 2022-12-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0013_supplier_social_facebook_supplier_social_instagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='fact_heading',
        ),
    ]
