# Generated by Django 4.1.2 on 2022-12-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0019_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
