# Generated by Django 4.1.2 on 2022-12-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0020_alter_supplier_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='logo_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='marketing_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='models/'),
        ),
    ]
